### ISSUE TITLE
How to reload contentview?

### ISSUE THREAD

**Issue by ghost** [honcheng/PaperFold-for-iOS#26]
I try to make menu based on paperfold. I have UITableView as a leftview and UIViewController as content view. How can I change view controller in contentview from table cell from left view? My project based on PaperFold-Containment View.

**Comment by honcheng** [comment]
Hi,

If you are swapping UIViewController in the content view, it should be using containment view. But the PaperFold-Containment View demo project is wrongly named, because that doesn't make use of containment view. 

I've created a new github project here just for this 
https://github.com/honcheng/PaperFoldMenuController
It uses PaperFold-for-iOS as a submodule. I think it is probably better that I separate this project instead of trying to add everything here.
